#server:
#  port: 8080
#  name: Test
#  servlet:
#    context-path: /
#
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: root@123
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 500MB
#      max-request-size: 500MB
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#
#fileUploadPath: /home/ubuntu/uploads/
